"""
Phase 6A: Push Discovery Playlists to Subsonic

Reads M3U files generated by phase5_inference.py, resolves each file path to a
Subsonic song ID (via search3 API with local JSON cache), then creates or
replaces the named playlists in Subsonic.

Run on the seedbox after copying playlists from RunPod:
    scp -r root@RUNPOD_IP:/workspace/playlistai/playlists ~/playlistai/playlists
    python phase6_push.py [--playlist-dir ~/playlistai/playlists]

Environment variables (or set in .env):
    SUBSONIC_URL, SUBSONIC_USER, SUBSONIC_PASS, SUBSONIC_MUSIC_ROOT
"""

import json
import logging
import argparse
import urllib.request
import urllib.parse
import re
from pathlib import Path

from config import (
    SUBSONIC_URL, SUBSONIC_USER, SUBSONIC_PASS,
    SUBSONIC_API_VERSION, SUBSONIC_CLIENT,
    SUBSONIC_MUSIC_ROOT,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.FileHandler("phase6_push.log"),
        logging.StreamHandler(),
    ],
)
log = logging.getLogger(__name__)

# Persistent local cache: absolute_path → Subsonic song ID
CACHE_FILE = "subsonic_id_cache.json"


# ── Subsonic API ───────────────────────────────────────────────────────────────

def _api(endpoint: str, **params) -> dict:
    """Make a Subsonic REST API call and return the inner response object."""
    base = SUBSONIC_URL.rstrip("/")
    qs = urllib.parse.urlencode({
        "u": SUBSONIC_USER,
        "p": SUBSONIC_PASS,
        "v": SUBSONIC_API_VERSION,
        "c": SUBSONIC_CLIENT,
        "f": "json",
        **params,
    })
    url = f"{base}/rest/{endpoint}?{qs}"
    with urllib.request.urlopen(url, timeout=120) as resp:
        data = json.loads(resp.read())
    outer = data["subsonic-response"]
    if outer["status"] != "ok":
        raise RuntimeError(f"Subsonic error on {endpoint}: {outer.get('error')}")
    return outer


def _api_post(endpoint: str, song_ids: list[str], **params) -> dict:
    """
    POST variant for createPlaylist — avoids URL-length limits when passing
    many songId parameters.
    """
    base = SUBSONIC_URL.rstrip("/")
    url = f"{base}/rest/{endpoint}"
    body_params = [
        ("u", SUBSONIC_USER), ("p", SUBSONIC_PASS),
        ("v", SUBSONIC_API_VERSION), ("c", SUBSONIC_CLIENT), ("f", "json"),
        *params.items(),
        *[("songId", sid) for sid in song_ids],
    ]
    body = urllib.parse.urlencode(body_params).encode()
    req = urllib.request.Request(url, data=body)
    with urllib.request.urlopen(req, timeout=120) as resp:
        data = json.loads(resp.read())
    outer = data["subsonic-response"]
    if outer["status"] != "ok":
        raise RuntimeError(f"Subsonic error on {endpoint}: {outer.get('error')}")
    return outer


# ── Path → Subsonic ID resolution ─────────────────────────────────────────────

def _abs_to_rel(abs_path: str) -> str:
    """Strip SUBSONIC_MUSIC_ROOT prefix → Subsonic-relative path."""
    root = SUBSONIC_MUSIC_ROOT.rstrip("/") + "/"
    if abs_path.startswith(root):
        return abs_path[len(root):]
    return abs_path


def _search_song(rel_path: str) -> str | None:
    """
    Find the Subsonic song ID for a relative path.
    Searches by filename stem, then verifies the path suffix matches.
    Returns None if not found.
    """
    stem = Path(rel_path).stem
    # Remove common track-number prefixes for a cleaner search term
    query = re.sub(r"^\d+[\s\-_.]+", "", stem).strip() or stem

    try:
        data = _api("search3", query=query, artistCount=0, albumCount=0, songCount=20)
        songs = data.get("searchResult3", {}).get("song", [])
    except Exception as e:
        log.warning("search3 failed for '%s': %s", query, e)
        return None

    # Match by relative path suffix (Subsonic may store os.sep variants)
    for song in songs:
        song_path = song.get("path", "").replace("\\", "/")
        if song_path == rel_path or song_path.endswith("/" + rel_path):
            return str(song["id"])

    # Fallback: match by filename only (useful when Subsonic root differs)
    filename = Path(rel_path).name
    for song in songs:
        if Path(song.get("path", "")).name == filename:
            return str(song["id"])

    return None


def _resolve_ids(file_paths: list[str], cache: dict) -> tuple[list[str], int]:
    """
    Resolve a list of absolute file paths to Subsonic song IDs.
    Returns (list_of_ids, miss_count).
    """
    ids = []
    misses = 0
    for abs_path in file_paths:
        if abs_path in cache:
            ids.append(cache[abs_path])
            continue

        rel_path = _abs_to_rel(abs_path)
        song_id = _search_song(rel_path)
        if song_id:
            cache[abs_path] = song_id
            ids.append(song_id)
        else:
            log.warning("  Could not resolve: %s", abs_path)
            misses += 1

    return ids, misses


# ── M3U parsing ────────────────────────────────────────────────────────────────

def _parse_m3u(m3u_path: str) -> list[str]:
    """Return list of absolute file paths from an M3U file."""
    paths = []
    with open(m3u_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                paths.append(line)
    return paths


# ── Subsonic playlist management ───────────────────────────────────────────────

def _get_existing_playlists() -> dict[str, str]:
    """Return dict: playlist_name → playlist_id for all playlists on server."""
    data = _api("getPlaylists")
    playlists = data.get("playlists", {}).get("playlist", [])
    return {pl["name"]: str(pl["id"]) for pl in playlists}


def _push_playlist(name: str, song_ids: list[str], existing: dict[str, str]) -> str:
    """
    Create or replace a Subsonic playlist.
    Returns 'created' or 'updated'.
    """
    if name in existing:
        _api_post("createPlaylist", song_ids, playlistId=existing[name])
        return "updated"
    else:
        _api_post("createPlaylist", song_ids, name=name)
        return "created"


# ── Main ───────────────────────────────────────────────────────────────────────

def push_playlists(playlist_dir: str = "playlists") -> None:
    if not SUBSONIC_URL:
        raise RuntimeError("SUBSONIC_URL is not set. Check your .env file.")

    m3u_files = sorted(Path(playlist_dir).glob("*.m3u"))
    if not m3u_files:
        log.error("No M3U files found in %s", playlist_dir)
        return

    log.info("Found %d M3U files in %s", len(m3u_files), playlist_dir)

    # Load persistent path→id cache
    cache: dict[str, str] = {}
    if Path(CACHE_FILE).exists():
        with open(CACHE_FILE) as f:
            cache = json.load(f)
        log.info("Loaded %d cached path→ID mappings", len(cache))

    # Fetch existing Subsonic playlists once
    log.info("Fetching existing Subsonic playlists …")
    existing = _get_existing_playlists()
    log.info("%d playlists already on server", len(existing))

    results = []
    total_misses = 0

    for m3u_path in m3u_files:
        playlist_name = m3u_path.stem      # filename without .m3u
        file_paths    = _parse_m3u(str(m3u_path))

        if not file_paths:
            log.info("Skipping empty playlist: %s", playlist_name)
            continue

        log.info("Resolving %d songs for '%s' …", len(file_paths), playlist_name)
        song_ids, misses = _resolve_ids(file_paths, cache)
        total_misses += misses

        if not song_ids:
            log.warning("  No songs resolved for '%s' — skipping", playlist_name)
            results.append((playlist_name, 0, misses, "skipped"))
            continue

        action = _push_playlist(playlist_name, song_ids, existing)
        log.info(
            "  '%s' %s (%d songs, %d unresolved)",
            playlist_name, action, len(song_ids), misses,
        )
        results.append((playlist_name, len(song_ids), misses, action))

    # Save updated cache
    with open(CACHE_FILE, "w") as f:
        json.dump(cache, f)
    log.info("Path cache saved (%d entries) → %s", len(cache), CACHE_FILE)

    # Summary
    print("\n" + "=" * 60)
    print("PLAYLISTAI — PHASE 6A PUSH SUMMARY")
    print("=" * 60)
    for name, count, misses, action in results:
        flag = " (!)  " if misses else "      "
        print(f"  {flag}{action:8s}  {count:>4} songs  ({misses} unresolved)  {name}")
    print(f"\n  Total unresolved paths : {total_misses}")
    if total_misses > 0:
        print("  Re-run after fixing unresolved paths — cache means resolved songs are free.")
    print("=" * 60)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Push discovery playlists to Subsonic")
    parser.add_argument(
        "--playlist-dir", default="playlists",
        help="Directory containing M3U files (default: %(default)s)",
    )
    args = parser.parse_args()
    push_playlists(args.playlist_dir)
